### ISSUE TITLE
Create Levels

### ISSUE THREAD

**Issue by crombach** [tz0/game#102]
NOTE: Levels (and perhaps more importantly, the level camera) should have a 160:81 aspect ratio so there is no distortion when turning TECH-17.

_Serene_ will have 12 levels which tell our story. Gameplay mechanics will be gradually introduced throughout the course of the game. The following is a rough outline of mechanics introduction. Story can be decided later on.

- [x] Level 1 (introduce entrance, exit, fuel and oxygen systems)
- [x] Level 2 (introduce fans)
- [x] Level 3
- [x] Level 4 (introduce lethal walls)
- [x] Level 5 
- [x] Level 6 (introduce shock boxes)
- [x] Level 7 
- [x] Level 8 (introduce black hole / pressure source)
- [x] Level 9
- [x] Level 10
- [x] Level 11
- [x] Level 12 (finish story)

**Comment by crombach** [comment]
Levels 1-5: Erik
Levels 6-7: Yangyang
Levels 8-12: Tao

**Comment by narrative** [comment]
Maybe we should just specify the width in the level, and have the height be calculated. This will take away the chance of screwing up the aspect ratio.

**Comment by crombach** [comment]
That works for the camera, but you still have to manually specify walls.

**Comment by crombach** [comment]
We need to make sure all levels are properly balanced before Thursday. That means making sure fuel and oxygen are at an appropriately difficult level, and that all level designs are solid.
