### ISSUE TITLE
No exceptions

### ISSUE THREAD

**Issue by narrative** [tz0/game#11]
Currently ResourceManager fails by throwing an exception when a texture/sound is not found. Consider changing this to display a warning message in the console to allow the game to not crash.

**Comment by crombach** [comment]
This can be accomplished by having a texture that is a red X (or something like that) that loads whenever a texture fails to load and an error sound that loads whenever a sound fails to load. Along with a console message, this should be sufficient for allowing the game to continue running while making it clear that there was an error.
