### ISSUE TITLE
Game demo video

### ISSUE THREAD

**Issue by tz0** [tz0/game#116]
Need to create a demo video that demonstrates the game and its core mechanics. We should probably also outline the general story.

- [x] Record gameplay
- [x] Edit recorded gameplay
- [x] Narrate over gameplay
- [x] Mix gameplay and narration into one cohesive whole

**Comment by crombach** [comment]
Narration complete, on the Google drive.

**Comment by hyy369** [comment]
Uploaded to YouTube: https://youtu.be/utIs-i6PWqE
