### ISSUE TITLE
13 in progress.log causes seg fault

### ISSUE THREAD

**Issue by narrative** [tz0/game#117]
To reproduce:

1. Edit progress.log to contain the value 13.
2. Start the game.
3. Press enter

After beating level 12, a 13 is saved into progress.log, and after this, trying to enter the level select screen will cause the game to crash.

**Comment by hyy369** [comment]
Added lines in `ViewManager::ReadUnlockedLevel` and `ViewManager::WriteUnlockedLevel` so that it does not read/write numbers larger than total levels.
