### ISSUE TITLE
Fix Control Scaling

### ISSUE THREAD

**Issue by narrative** [tz0/game#18]
We want the Tech 17 player to be able to rotate freely (left and right arrows apply a torque to the body), and the jetpack's main thruster will cause him to move in the direction he is facing.

**Comment by crombach** [comment]
New controls implemented, but jetpack force seems to vary across different systems that run at different speeds. Rotation speed is fine.

**Comment by crombach** [comment]
Rotation speed is now implemented as torque, so it may be affected.
