### ISSUE TITLE
Menu System

### ISSUE THREAD

**Issue by crombach** [tz0/game#51]
Main Menu

- [x] Select Level
- [x] Exit Game

Level Select Menu

- [x] Display levels (in a grid). Clicking on a level (or selecting it and pressing enter) loads you into that level.
- [x] Main Menu

Pause / End Game Menu

- [x] Paused / You Win / You Lose message
- [x] Retry (If paused or you lose) / Next level (if you win)
- [x] Level Select
- [x] Exit Game

Navigation between menus and game

 - [x] State system

**Comment by hyy369** [comment]
State system is working. Able to switch between menus and games now.
Problem to fix:
- [ ]Game logic does not re-initialize when restarted a level

**Comment by hyy369** [comment]
- [ ] Change menu selections to buttons that can be navigated using arrows keys

**Comment by hyy369** [comment]
- [ ] Menu options can loop around
- [ ] Enhance menu look
- [ ] Add intermediate animations
