### ISSUE TITLE
Consolidate radius and width in level design files.

### ISSUE THREAD

**Issue by tz0** [tz0/game#69]
So far in the level.json, we specify walls with a `radius`, but fans using a `width`.  Maybe we can later on consolidate on one or the other.  A `radius` for walls makes sense because that’s how they are implemented internally so if we make them both the same way let’s use a `radius`.

**Comment by narrative** [comment]
I think we can close this. At this point it doesn't really matter and would be more effort than it's worth to go through and change all the existing levels.

**Comment by tz0** [comment]
Thanks.
