### ISSUE TITLE
Implement the level (file) reader for Resource Manager

### ISSUE THREAD

**Issue by tz0** [tz0/game#8]
Since we want to use percentage to simplify the location representation of every "actor" and we use our physics engine's origin, which is right in the center.  We probably want to create a small **conversion procedure**.  

The conversion procedure does simple things.  For example:

```
x_level_file = reader.read(leve_1, fan_1, x); // read a float number (as percentage) from json, it could be a fan's x location
x_level_sys = kLengthPlayground * x_level_file - (kLengthPlayground / 2) // transform convert it into an valid value for the physics system
```
However, just something we need to keep an eye on.  Open to discussion.

TODO: reformat the current level file:
- add camera information
- remove endpoints

**Comment by crombach** [comment]
Need to add a level parameter for camera origin and size.
